### ISSUE TITLE
Matinenace / Updating

### ISSUE THREAD

**Issue by Radvendii** [ngi-nix/weblate#4]
Checking in to ask a couple of things about maintenance

1. Is this project being maintained / are there plans to maintain it?
2. Is it possible to make an update script that encapsulates the process you went through to produce e.g. `pyproject.toml` in the first place?
3. If not, maybe you can write down a description somewhere so a human can follow the same steps

Thanks!

**Comment by erictapen** [comment]
Hi, for the past years I tried to keep this module up to date with the latest version, but recently I've had a hard time keeping up. So it is probably better to see this as unmaintained.

Updating `pyproject.toml` unfortunately involves quite a bit of manual labor, but I'll try to add some info about the process to the README.
